tag: dev

api:
  replicaCount: 1
  image: okteto.dev/api

mongoUrl: mongodb://mongo/test
accessTokenSecret: CHANGE_THIS_SUPER_SECRET_ACCESS_TOKEN_SECRET
refreshTokenSecret: CHANGE_THIS_SUPER_SECRET_ACCESS_TOKEN_SECRET