apiVersion: v1
kind: Secret
metadata:
  name: token
  labels:
    app.kubernetes.io/component: token
    {{- include "usuarios.labels" . | nindent 4 }}
type: Opaque
data:
  access_token_secret:  {{ .Values.accessTokenSecret | b64enc }}
  refresh_token_secret:  {{ .Values.refreshTokenSecret | b64enc }}
