name: Okteto Deployment Pedro

on:
  push:
    branches: [ master ]

jobs:
  test:
    uses: MUISCDGTI/Usuarios/.github/workflows/tests.yml@master
    
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Okteto Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_PEDRO }}
          
      - name: Okteto Pipeline
        uses: okteto/pipeline@latest
        with:
          # The name of the pipeline
          name: usuarios
          # If present, the namespace scope for this action. If not specified, it will use the current context
          namespace: fis-gfpedro
