# This is a basic workflow to help you get started with Actions

name: Okteto Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

jobs:
  test:
    uses: MUISCDGTI/Usuarios/.github/workflows/tests.yaml@main
    
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Okteto Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          
      - name: Okteto Pipeline
        uses: okteto/pipeline@latest
        with:
          name: fis-usuarios-backend
          namespace: fis-julgargal

